/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * radioYCombo.java
 *
 * Created on 25/02/2012, 12:16:14 PM
 */

package Frames;

/**
 *
 * @author maestroe
 */
public class radioYCombo extends javax.swing.JFrame {

    /** Creates new form radioYCombo */
    public radioYCombo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hobbies = new javax.swing.ButtonGroup();
        equipos = new javax.swing.ButtonGroup();
        cbLeer = new javax.swing.JCheckBox();
        rbChivas = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblHobbie = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbLeones = new javax.swing.JRadioButton();
        rbAtlas = new javax.swing.JRadioButton();
        rbTecos = new javax.swing.JRadioButton();
        cbTV = new javax.swing.JCheckBox();
        cbDeporte = new javax.swing.JCheckBox();
        cbMascota = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hobbies.add(cbLeer);
        cbLeer.setText("Leer");
        cbLeer.setToolTipText("El checkbox");

        equipos.add(rbChivas);
        rbChivas.setText("Chivas");

        lblHobbie.setText("Hobbie");

        jLabel2.setText("Equipos de Guadalajara");

        equipos.add(rbLeones);
        rbLeones.setText("LEONES NEGROS!!!!!!!!!!!!!");

        equipos.add(rbAtlas);
        rbAtlas.setText("Atlas");

        equipos.add(rbTecos);
        rbTecos.setText("Tecos");

        hobbies.add(cbTV);
        cbTV.setText("Ver Tv");

        hobbies.add(cbDeporte);
        cbDeporte.setText("Hacer deporte");

        hobbies.add(cbMascota);
        cbMascota.setText("Mascota");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbLeer)
                                    .addComponent(cbTV))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbMascota)
                                    .addComponent(cbDeporte)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbChivas)
                                    .addComponent(rbAtlas))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbTecos)
                                    .addComponent(rbLeones)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblHobbie)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHobbie)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbLeer)
                    .addComponent(cbDeporte))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTV)
                    .addComponent(cbMascota))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbChivas)
                    .addComponent(rbLeones))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbAtlas)
                    .addComponent(rbTecos))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new radioYCombo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbDeporte;
    private javax.swing.JCheckBox cbLeer;
    private javax.swing.JCheckBox cbMascota;
    private javax.swing.JCheckBox cbTV;
    private javax.swing.ButtonGroup equipos;
    private javax.swing.ButtonGroup hobbies;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblHobbie;
    private javax.swing.JRadioButton rbAtlas;
    private javax.swing.JRadioButton rbChivas;
    private javax.swing.JRadioButton rbLeones;
    private javax.swing.JRadioButton rbTecos;
    // End of variables declaration//GEN-END:variables

}
