/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Menu.java
 *
 * Created on 15-mar-2012, 22:01:58
 */

package Frames;

/**
 *
 * @author humberto
 */
public class Menu extends javax.swing.JFrame {

    /** Creates new form Menu */
    public Menu() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        MenuCerrar = new javax.swing.JMenuItem();
        MenuSeleccion = new javax.swing.JMenu();
        menuDiscos = new javax.swing.JMenuItem();
        menuListas = new javax.swing.JMenuItem();
        menuFormulario = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuArchivo.setText("Archivo");

        MenuCerrar.setText("Cerrar");
        MenuCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickEnCerrar(evt);
            }
        });
        menuArchivo.add(MenuCerrar);

        menu.add(menuArchivo);

        MenuSeleccion.setText("Seleccion");

        menuDiscos.setText("Discos");
        menuDiscos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickEnDiscos(evt);
            }
        });
        MenuSeleccion.add(menuDiscos);

        menuListas.setText("Listas");
        menuListas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickEnListas(evt);
            }
        });
        MenuSeleccion.add(menuListas);

        menuFormulario.setText("Formulario");
        menuFormulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickEnFormulario(evt);
            }
        });
        MenuSeleccion.add(menuFormulario);

        menuUsuarios.setText("Usuarios");
        menuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickEnUsuarios(evt);
            }
        });
        MenuSeleccion.add(menuUsuarios);

        menu.add(MenuSeleccion);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClickEnDiscos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClickEnDiscos
    Discos cds=new Discos();
    cds.setVisible(true);
    }//GEN-LAST:event_ClickEnDiscos

    private void ClickEnListas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClickEnListas
    Listas list=new Listas();
    list.setVisible(true);
    }//GEN-LAST:event_ClickEnListas

    private void ClickEnFormulario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClickEnFormulario
    Formulario form=new Formulario();
    form.setVisible(true);
    }//GEN-LAST:event_ClickEnFormulario

    private void ClickEnUsuarios(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClickEnUsuarios
    Usuarios usr=new Usuarios();
    usr.setVisible(true);
    }//GEN-LAST:event_ClickEnUsuarios

    private void ClickEnCerrar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClickEnCerrar
        this.dispose();  //Cierra la aplicacion
    }//GEN-LAST:event_ClickEnCerrar

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuCerrar;
    private javax.swing.JMenu MenuSeleccion;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuItem menuDiscos;
    private javax.swing.JMenuItem menuFormulario;
    private javax.swing.JMenuItem menuListas;
    private javax.swing.JMenuItem menuUsuarios;
    // End of variables declaration//GEN-END:variables

}
